In [2]:
import pandas as pd
lm = pd.read_csv("Depth_180511.txt")
old_z = lm["Z"].copy()

distance_col = "M3C2 interp"
lm["//X"] -= lm["Nx"] * lm[distance_col]
lm["Y"] -= lm["Ny"] * lm[distance_col]
lm["Z"] -= lm["Nz"] * lm[distance_col]

lm = lm[~lm.Y.isnull()]



lm[["//X", "Y", "Z", distance_col, "Nx", "Ny", "Nz"]].to_csv("Depth_offset_180511.txt", index=False)
lm.head()

,//X,Y,Z,Original cloud index,M3C2 interp,M3C2 distance,Nx,Ny,Nz
0,652004.19922,7.558889e+06,1746.18604,0.0,0.0,0.0,0.036774,0.486239,0.873052
1,652010.56250,7.558881e+06,1750.65210,0.0,0.0,0.0,0.050291,0.452618,0.890285
2,652015.28516,7.558896e+06,1741.83508,0.0,0.0,0.0,0.039588,0.487347,0.872310
3,652016.36328,7.558874e+06,1754.01550,0.0,0.0,0.0,0.055353,0.419871,0.905894
4,652020.49609,7.558907e+06,1735.19470,0.0,0.0,0.0,0.028582,0.502226,0.864264